const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = {};
const path = require('node:path').join(__dirname, '../StudioModel.js');
if (fs.existsSync(path)) vm.runInNewContext(fs.readFileSync(path, 'utf8'), context);
assert.equal(typeof context.recommendedSetup, 'function');
const T = require('../TopologyModel.js');
const d = (name, x=0) => ({name, enabled:true, width:1920,height:1080,refreshRate:144,scale:1,transform:0,x,y:0,availableModes:['1920x1080@144Hz','1920x1080@60Hz']});
const displays = [d('DP-1'), d('HDMI-A-1')];
const original = JSON.stringify(displays);
let plan = context.recommendedSetup(displays, 'extend', T);
assert.equal(plan.valid,true);
assert.equal(plan.proposed.length,2);
assert.equal(plan.proposed[1].x,1920);
assert.equal(plan.proposed[0].refreshRate,60);
assert.equal(JSON.stringify(displays),original);
plan = context.recommendedSetup(displays, 'mirror', T);
assert.equal(plan.valid,true);
assert.equal(plan.proposed[1].mirrorOf,'DP-1');
assert.equal(plan.proposed[1].x,0);
assert.equal(context.recommendedSetup([d('DP-1'),{...d('DP-2'),availableModes:[]}], 'extend', T).valid,false);
assert.equal(context.recommendedSetup(displays, 'bogus', T).valid,false);
assert.equal(typeof context.displayHealth,'function');
let health = context.displayHealth(displays, {status:'weak'}, {}, false, T);
assert(health.issues.some(i => i.code === 'overlap'));
assert(health.issues.some(i => i.code === 'identity-uncertain'));
assert.equal(health.repairable,true);
health = context.displayHealth([d('DP-1'), {...d('DP-2',1920),enabled:false}], {status:'exact'}, {'1':'missing'}, false, T);
assert(health.issues.some(i => i.code === 'disabled'));
assert(health.issues.some(i => i.code === 'workspace-unavailable'));
health = context.displayHealth([{...d('<serial-secret>'),availableModes:[]}], {status:'exact'}, {}, false, T);
assert(health.issues.some(i => i.code === 'modes-unknown'));
assert.equal(health.repairable,false);
const report = context.sanitizedReport([{...d('serial-secret'),serial:'SECRET',sysfsPath:'/home/private',description:'<img src="file:///secret">'}],{status:'weak',profileId:'private'}, {}, true, T);
assert(!/SECRET|secret|private|file:|serial/.test(report));
assert.match(report,/1920/);
assert.match(report,/transitioning/);
assert.equal(JSON.stringify(displays),original);
console.log('studio model tests passed');
